


diet1: 
	glpsol \
	--model diet.ampl \
	--data diet.data \
	--output diet.out

diet2: 
	glpsol \
	--model diet2.ampl \
	--data diet.data \
	--output diet.out

diet3: 
	glpsol \
	--model diet3.ampl \
	--data diet.data \
	--output diet.out

clean:
	rm -rf diet.out
